apiVersion: apps/v1
kind: Deployment
metadata:
  name: trex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: trex
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: trex
    spec:
      containers:
        - image: quay.io/sclorg/postgresql-15-c8s:latest
          imagePullPolicy: Always
          name: psql
          env:
            - name: POSTGRESQL_DATABASE
              value: rhtrex
            - name: POSTGRESQL_PASSWORD
              value: foobar-bizz-buzz
            - name: POSTGRESQL_USER
              value: trex
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 10m
              memory: 512Mi       
        - image: trex
          imagePullPolicy: Always
          name: trex
          ports:
            - containerPort: 8000
          command: ["sh", "-c"]
          args:
          - |
            /rh-trex/trex migrate
            /rh-trex/trex serve --api-server-bindaddress=0.0.0.0:8000
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
             