apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.service.group: trex
  creationTimestamp: null
  labels:
    io.kompose.service: trex
  name: trex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trex
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.service.expose: "true"
        kompose.service.group: trex
      creationTimestamp: null
      labels:
        io.kompose.network/rh-trex-default: "true"
        io.kompose.service: trex
    spec:
      volumes:
        - configMap:
            name: trex-init-cm0
          name: trex-init-cm0    
      containers:
        - command: ["sh", "-c"]
          args:
          - |
            /rh-trex/trex migrate
            /rh-trex/trex serve --api-server-bindaddress=0.0.0.0:8000
          image: trex
          name: trex
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /rh-trex/secrets
              name: trex-init-cm0
          resources: {}     
        - env:
            - name: POSTGRESQL_DATABASE
              value: rhtrex
            - name: POSTGRESQL_PASSWORD
              value: foobar-bizz-buzz
            - name: POSTGRESQL_USER
              value: trex
          image: quay.io/sclorg/postgresql-15-c8s:latest
          livenessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: trex-db
          resources: {}
---
apiVersion: v1
data:
  db.host: |
    localhost
  db.name: |
    rhtrex
  db.password: |
    foobar-bizz-buzz
  db.port: "5432"
  db.user: |
    trex
  ocm-service.clientId: ocm-ams-testing
  ocm-service.clientSecret: your-client-secret-here
  ocm-service.token: your-ocm-api-token-here
  sentry.key: |
    your-key-here-for-dev-or-mounted-by-volume-in-a-deployment
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: trex-init
  name: trex-init-cm0


             